# Generated by Django 3.1.6 on 2021-04-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210402_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Фото автора'),
        ),
    ]
