# Generated by Django 3.1.6 on 2021-04-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210402_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='banner',
            field=models.CharField(blank=True, max_length=250, verbose_name='Баннер'),
        ),
    ]
