# Generated by Django 3.1.6 on 2021-03-15 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_ru', models.CharField(max_length=25, verbose_name='Должность игрока')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='ID игрока')),
                ('name', models.CharField(max_length=25, verbose_name='Имя игрока')),
                ('battles', models.CharField(blank=True, max_length=25, verbose_name='Всего боев')),
                ('wgr', models.CharField(blank=True, max_length=25, verbose_name='WGR')),
                ('win', models.CharField(blank=True, max_length=25, verbose_name='Процент побед')),
                ('damage', models.CharField(blank=True, max_length=25, verbose_name='Средний дамаг')),
                ('frags', models.CharField(blank=True, max_length=25, verbose_name='Среднее кол-во фрагов')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clanid')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.clanrole')),
            ],
            options={
                'verbose_name': 'Игрок клана',
                'verbose_name_plural': 'Игроки клана',
                'ordering': ('role_id',),
            },
        ),
    ]
