# Generated by Django 3.1.6 on 2021-03-19 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название роты')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет роты')),
            ],
            options={
                'verbose_name': 'Рота',
                'verbose_name_plural': 'Роты',
            },
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.clanteam'),
        ),
    ]
