# Generated by Django 3.1.6 on 2021-03-23 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20210319_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Имя игрока'),
        ),
        migrations.AlterField(
            model_name='players',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.clanrole'),
        ),
    ]
