# Generated by Django 3.1.6 on 2021-04-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20210323_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='wn8',
            field=models.CharField(blank=True, max_length=25, verbose_name='Wn8'),
        ),
    ]
