# Generated by Django 3.1.6 on 2021-04-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_players_wn8'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='color_wn8',
            field=models.CharField(blank=True, max_length=6, verbose_name='Цвет Wn8'),
        ),
    ]
