# Generated by Django 3.1.6 on 2021-04-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_players_color_wn8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='color_wn8',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет Wn8'),
        ),
    ]
