# Generated by Django 3.1.6 on 2021-04-10 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20210410_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.clanteam'),
        ),
    ]
