# Generated by Django 3.1.6 on 2021-04-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210402_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='streamer',
            field=models.BooleanField(default=False, verbose_name='Стример'),
        ),
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ссылка на канал'),
        ),
    ]
