# Generated by Django 3.1.6 on 2021-04-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210403_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.CharField(blank=True, max_length=300, verbose_name='Фото игрока'),
        ),
    ]
