# Generated by Django 3.1.6 on 2021-04-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210404_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=500, verbose_name='Токен'),
        ),
    ]
