# Generated by Django 3.1.6 on 2021-04-04 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20210323_0329'),
        ('users', '0005_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.players'),
        ),
    ]
