# Generated by Django 3.1.6 on 2021-04-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210404_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='player',
        ),
    ]
