# Generated by Django 3.1.6 on 2021-04-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20210323_0329'),
        ('users', '0008_remove_profile_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.players'),
        ),
    ]
