# Generated by Django 3.1.6 on 2021-04-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=400, verbose_name='Токен'),
        ),
    ]
