# Generated by Django 3.1.6 on 2021-04-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20210410_0419'),
        ('interview', '0002_auto_20210416_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='players.Players', verbose_name='Проголосовали'),
        ),
    ]
