# Generated by Django 3.1.6 on 2021-04-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20210410_0419'),
        ('interview', '0004_question_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='players.Players', verbose_name='Отвечающие'),
        ),
    ]
