# Generated by Django 3.1.6 on 2021-04-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20210416_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Публичный?'),
        ),
    ]
