# Generated by Django 3.1.6 on 2021-03-15 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClanId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_id', models.CharField(max_length=7, verbose_name='ID клана')),
            ],
            options={
                'verbose_name': 'ID клана',
                'verbose_name_plural': 'ID клана',
            },
        ),
        migrations.CreateModel(
            name='ClanInfo',
            fields=[
                ('tag', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Тэг клана')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Название клана')),
                ('motto', models.CharField(blank=True, max_length=100, verbose_name='Девиз клана')),
                ('color', models.CharField(blank=True, max_length=10, verbose_name='Цвет клана')),
                ('emblem', models.CharField(blank=True, max_length=300, verbose_name='Эмблема клана')),
            ],
            options={
                'verbose_name': 'Информация о клане',
                'verbose_name_plural': 'Информация о клане',
            },
        ),
        migrations.CreateModel(
            name='ClanStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh10', models.CharField(blank=True, max_length=4, verbose_name='Эло укрепрайона X')),
                ('sh8', models.CharField(blank=True, max_length=4, verbose_name='Эло укрепрайона VIII')),
                ('sh6', models.CharField(blank=True, max_length=4, verbose_name='Эло укрепрайона VI')),
                ('gm10', models.CharField(blank=True, max_length=4, verbose_name='Эло глобальной карты X')),
                ('gm8', models.CharField(blank=True, max_length=4, verbose_name='Эло глобальной карты VIII')),
                ('gm6', models.CharField(blank=True, max_length=4, verbose_name='Эло глобальной карты VI')),
                ('battles_count', models.CharField(blank=True, max_length=10, verbose_name='Среднее кол-во боев')),
                ('win_rate', models.CharField(blank=True, max_length=10, verbose_name='Среднее процент побед')),
                ('rate', models.CharField(blank=True, max_length=10, verbose_name='Рейтинг клана')),
                ('position', models.CharField(blank=True, max_length=10, verbose_name='Позиция клана')),
                ('xp_per_battle', models.CharField(blank=True, max_length=10, verbose_name='Средний опыт за бой')),
                ('damage_per_battle', models.CharField(blank=True, max_length=10, verbose_name='Средний урон за бой')),
                ('static_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления статистики')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clanid')),
            ],
            options={
                'verbose_name': 'Статистика клане',
                'verbose_name_plural': 'Статистика клане',
            },
        ),
    ]
