# Generated by Django 3.1.6 on 2021-03-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanstatistic',
            name='clan',
        ),
        migrations.AlterField(
            model_name='clanid',
            name='clan_id',
            field=models.CharField(max_length=6, verbose_name='ID клана'),
        ),
        migrations.AlterField(
            model_name='claninfo',
            name='color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет клана'),
        ),
        migrations.AlterField(
            model_name='claninfo',
            name='tag',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Тэг клана'),
        ),
    ]
