# Generated by Django 3.1.6 on 2021-04-11 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210319_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clanstatistic',
            options={'verbose_name': 'Статистика клана', 'verbose_name_plural': 'Статистика клана'},
        ),
    ]
